// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: files.sql

package data

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    id,
    user_id,
    filename,
    data,
    uploaded_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, filename, data, uploaded_at
`

type CreateFileParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Filename   string
	Data       []byte
	UploadedAt time.Time
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.UserID,
		arg.Filename,
		arg.Data,
		arg.UploadedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.Data,
		&i.UploadedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, filename, data, uploaded_at FROM files
WHERE id = $1 AND user_id = $2
`

type GetFileByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetFileByID(ctx context.Context, arg GetFileByIDParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.Data,
		&i.UploadedAt,
	)
	return i, err
}

const getFilesByUserID = `-- name: GetFilesByUserID :many
SELECT 
    id,
    filename,
    uploaded_at
FROM files
WHERE user_id = $1
ORDER BY uploaded_at DESC
`

type GetFilesByUserIDRow struct {
	ID         uuid.UUID
	Filename   string
	UploadedAt time.Time
}

func (q *Queries) GetFilesByUserID(ctx context.Context, userID uuid.UUID) ([]GetFilesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesByUserIDRow
	for rows.Next() {
		var i GetFilesByUserIDRow
		if err := rows.Scan(&i.ID, &i.Filename, &i.UploadedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
