// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Filename   string
	Data       []byte
	UploadedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
